### PR TITLE
added some nicer error message when a provider is not found

### PR DESCRIPTION
**Pull request by BillKeenan**
Now looks like this, which should help troubleshooting provider issues

```
 Unable to find the requested .Net Framework Data Provider.  It may not be installed.

 I did find these       
 Factories:|System.Data.Odbc||System.Data.OleDb||System.Data.OracleClient||System.Data.SqlClient||System.Data.SqlServerCe.4.0|
```

### CODE REVIEW

**Comment by pinscript** [comment]
Thanks for this PR. Is it possible to catch a more specific exception?

**Comment by BillKeenan** [comment]
Sure, ill drop it in later
—
Thanks
Bill Keenan

**Comment by BillKeenan** [comment]
ok, updated in commit : 1ca88f7

**Comment by BillKeenan** [comment]
make that: 8824a21

**Comment by BillKeenan** [comment]
argh, i'd delete this if i could. I hadn't updated from your master for a while, so i did that as some of the handling right in this code was different.

Ok, updated in 59cbaab

**Comment by pinscript** [comment]
Thanks @BillKeenan, I really appreciate it.

**Pull request merged**
