### PR TITLE
Update the provider name to "MySql.Data.MySqlClient"

### PR DESCRIPTION
**Pull request by BillKeenan**
# Update the provider name to "MySql.Data.MySqlClient"

was previously default sqlclient

### CODE REVIEW

**Comment by pinscript** [comment]
This PR looks good, thank you!

**Comment by BillKeenan** [comment]
fun. my first PR

**Comment by pinscript** [comment]
@billCreativeD Just wanted to let you know that I dont actively use or maintain this project anymore. If you use it, i'l glady add you as a administrator.

**Comment by BillKeenan** [comment]
Sure,

I've been using it for some simple data migration tasks where i dont want
to have a strongly typed library, or nhibernate mappings etc..

What do you use for such tasks?

**Comment by pinscript** [comment]
Funny, i've been doing data migrations for the past few weeks. This time I went with Rhino ETL. It works pretty nice, but there is almost no documentation.

**Comment by BillKeenan** [comment]
ah, we all bow to ayende. I took the raven course in NYC last month with
him.

**Pull request merged**
